#!/bin/bash
read -p " bhai kaisa hai " b
echo '-----------------------------------------------------------------------------------------------------------------------------------------------'

if [ "$b" = "good" ]; then
	echo " mai bhi badiya hu"
	echo '---------------------------------------------------------------------------------------------------------------------------------------'

else
	echo "jab tak good nahi bolega tab tak script aage nai badega bhai"
	echo "good likh bhai"
	./start
fi



echo '-----------------------------------------------------------------------------------------------------------------------------------------------'

echo "agar no likh ga to script aage nahi run hogi bhai"
echo "yakin nahi to to no ya kuch bhi likh kar dekh le script restart ho jaayegi"
echo '-----------------------------------------------------------------------------------------------------------------------------------------------'
read -p "Do you want to run the code? (yes/no) " a

if [ "$a" = "yes" ]; then
	./step1_terraform
else
	echo "Bhai tune yes nahi likha"
	sleep 1
	echo "Pahle yes likh tabhi code run hoga"
	./start
fi
